#--------------------------------------------------
# NoCarrierMail Makefile (top) for Microsoft Visual C++
#--------------------------------------------------

CURS_DIR = \pdcurses
LIBS = $(CURS_DIR)\wincon\pdcurses.lib user32.lib advapi32.lib
COMPILER = $(CC) -nologo -c -O2 -D__WIN32__

all:	ncmail

O = obj

.SUFFIXES: .cc

{mmail}.cc.obj::
	$(COMPILER) $<

{interfac}.cc.obj::
	$(COMPILER) -I$(CURS_DIR) $<

MOBJS = misc.$(O) resource.$(O) mmail.$(O) filelist.$(O) netadd.$(O) \
area.$(O) letter.$(O) read.$(O) compress.$(O) pktbase.$(O) bw.$(O) \
qheader.$(O) qwk.$(O) qwkhdr.$(O) qwkvote.$(O) omen.$(O) soup.$(O) opx.$(O)

IOBJS = mmcolor.$(O) mysystem.$(O) isoconv.$(O) basic.$(O) interfac.$(O) \
packet.$(O) arealist.$(O) letterl.$(O) letterw.$(O) lettpost.$(O) \
ansiview.$(O) addrbook.$(O) tagline.$(O) help.$(O) main.$(O)

ncmail:	$(MOBJS) $(IOBJS)
	link -out:ncmail.exe *.obj $(LIBS)

clean:
	del *.obj
	del ncmail.exe

!include depend
