#-----------------------------------------------
# NoCarrierMail Makefile (top) for Borland/Turbo C++
#-----------------------------------------------

!ifndef CURS_DIR
CURS_DIR = \pdcurses
!endif

!if $(SYS) == DOS
LIBS = spawnl.lib $(CURS_DIR)\dos\pdcurses.lib
!else
LIBS = $(CURS_DIR)\wincon\pdcurses.lib
CC = bcc32c -q -D__WIN32__
!endif

LIST = tclist
COMPILER = $(CC) -c -P

O = obj

OPTS = -Immail -Iinterfac

.SUFFIXES: .cc

.autodepend

{mmail}.cc.obj:
	$(COMPILER) $(OPTS) $<

{interfac}.cc.obj:
	$(COMPILER) $(OPTS) -I$(CURS_DIR) $<

MOBJS = misc.$(O) resource.$(O) mmail.$(O) filelist.$(O) netadd.$(O) \
area.$(O) letter.$(O) read.$(O) compress.$(O) pktbase.$(O) bw.$(O) \
qheader.$(O) qwk.$(O) qwkhdr.$(O) omen.$(O) soup.$(O) opx.$(O)

IOBJS = mmcolor.$(O) mysystem.$(O) isoconv.$(O) basic.$(O) interfac.$(O) \
packet.$(O) arealist.$(O) letterl.$(O) letterw.$(O) lettpost.$(O) \
ansiview.$(O) addrbook.$(O) tagline.$(O) help.$(O) main.$(O)

all:	ncmail

ncmail:	$(MOBJS) $(IOBJS)
	$(CC) -encmail @$(LIST) $(LIBS)

clean:
	del *.obj
	del ncmail.exe
        del ncmail.tds
